
O número de albatrozes varia, consoante o autor, entre 13 e 24 espécies (incluindo os do género Phoebetria, ou piaus, que, para efeitos deste artigo, e de acordo com a nomenclatura internacional, serão considerados como "albatrozes"). Este é um assunto ainda em debate, ainda que o número mais aceite seja o de 21 espécies em 4 géneros: Diomedea (grandes albatrozes), Thalassarche (designados em inglês como mollymawks), Phoebastria (albatrozes do Pacífico Norte), e Phoebetria (os piaus). Os albatrozes do Pacífico Norte são considerados como um táxon-irmão dos grandes albatrozes, enquanto que os piaus se consideram como sendo mais próximos dos albatrozes do género Thalassarche.


Albatroz-errante.
A classificação taxonómica dos albatrozes também tem sido objecto de grande debate. A taxonomia de Sibley-Ahlquist propôs juntar as aves marinhas, aves de rapina e outras na alargada ordem das Ciconiiformes, enquanto que o International Ornithological Congress[1] e muitas organizações ornitológicas da América do Norte, Europa, África do Sul, Austrália e Nova Zelândia mantêm a tradicional ordem dos Procellariiformes. Os albatrozes distinguem-se dos outros Procellariiformes tanto em termos genéticos como pelas características morfológicas, nomeadamente no seu tamanho, forma das patas e arranjo das narinas tubulosas.[2]

Mesmo dentro da família taxonómica, a vinculação das espécies aos géneros tem-se prolongado há mais de um século. Colocados originalmente num só género, Diomedea, foram depois redistribuídos por Reichenbach em quatro géneros diferentes em 1852, seguindo-se outras reavaliações taxonómicas, podendo-se, em 1965, indicar 12 géneros diferentes propostos no total (ainda que cada classificação em específico nunca tenha ultrapassado os oito géneros): Diomedea, Phoebastria, Thalassarche, Phoebetria, Thalassageron, Diomedella, Nealbatrus, Rhothonia, Julietata, Galapagornis, Laysanornis, e Penthirenia.[3]

Em 1965, numa tentativa de dar alguma ordem à classificação destas aves, reuniram-se as espécies em dois géneros, Phoebetria (os piaus, que à primeira vista se parecem mais com os procelarídeos, e que eram considerados na altura como "primitivos" ) e Diomedea (os restantes).[4] Ainda que visando a simplificação da família em termos de nomenclatura, a classificação baseava-se na análise morfológica de Elliott Coues, datada de 1866, prestando pouca atenção a estudos mais recentes - além de ter ignorado mesmo algumas das sugestões de Coues.[3]


Relações filogenéticas entre os quatro géneros de albatroz. Baseado em Nunn et al, 1996.
Pesquisas mais recentes, da responsabilidade de Gary Nunn, do American Museum of Natural History (1996), e outros investigadores a nível internacional, estudaram o DNA mitocondrial das 14 espécies mais consensuais na época, parecendo demonstrar que o mais lógico é estabelecer quatro, e não dois, grupos monofiléticos dentro da família dos albatrozes.[5] Estes autores propuseram, então, a reabilitação de dois nomes dos antigos géneros: Phoebastria e Thalassarche, mantendo-se os grandes albatrozes no género Diomedea e os piaus no género Phoebetria. A British Ornithologists' Union, tal como autoridades ornitológicas da África do Sul dividiram os albatrozes em quatro géneros, de acordo com a sugestão de Nunn, tendo a mudança sido aceite pela maioria dos investigadores da área. [carece de fontes]

Mas, enquanto existe alguma unanimidade quanto ao número de géneros, mantém-se a discussão no que diz respeito ao número de espécies. Em termos históricos, já foram descritas mais de 80 por diferentes pesquisadores; muitas das quais resultavam da identificação equivocada de aves no seu estádio juvenil.[6] Baseando-se nas conclusões em torno da definição dos géneros de albatrozes, Robertson e Nunn propuseram em 1998 uma classificação taxonómica com 24 espécies diferentes,[3] em contraste com as 14 então aceites. Esta taxonomia interina promoveu muitas subespécies a espécies, mas foi muito criticada por não usar, em cada caso, informação submetida a revisão por pares que justificasse as divisões. Desde então que outros estudos aprovaram ou criticaram esta reavaliação taxonómica; um estudo de 2004, baseando-se na análise de DNA mitocondrial e microsatélites confirmou a hipótese de que o albatroz-das-antípodas e o albatroz-de-tristão eram espécies distintas do albatroz-errante, de acordo com Robertson e Nunn, mas que o sugerido albatroz-de-gibson, Diomedea gibsoni, não se distinguia do albatroz-das-antípodas.[7] Muitos organismos, incluindo a IUCN e diversos investigadores aceitam a classificação taxonómica interina de 21 espécies, ainda que não exista unanimidade científica quanto a esta; em 2004, Penhallurick e Wink sugeriram que o número de espécies fosse reduzido para 13 (incluindo a fusão do albatroz-de-amsterdam com o albatroz-errante,[8] mas o estudo foi particularmente controverso.[6][9] Todas as partes concordam, contudo, que é necessário um acordo geral que esclareça definitivamente o assunto. [carece de fontes]

O estudo molecular da evolução das famílias de aves, de acordo com a taxonomia de Sibley e Ahlquist, situa a radiação adaptativa dos Procellariiformes no Oligoceno (há 35–30 milhões de anos atrás), ainda que este grupo se tenha originado antes, como se depreende de um fóssil que é atribuído por alguns autores a esta ordem: uma ave marinha a que foi atribuído o género Tytthostonyx, encontrada em rochas do Cretáceo (há 70 milhões de anos atrás). Os estudos moleculares sugerem que os painhos foram os primeiros a divergir do ramo ancestral, seguindo-se os albatrozes, com os procelarídeos e os painhos-mergulhadores a autonomizarem-se mais tarde. Os fósseis mais antigos de albatroz foram encontrados em rochas que datam do Eoceno ao Oligoceno, ainda que alguns sejam vinculados a esta família apenas de forma provisória, além de que nenhum tem grandes semelhanças com as espécies actuais. São os géneros Murunkus (Eoceno Médio do Uzbequistão), Manu (Oligoceno inferior da Nova Zelândia), e uma forma não descrita do Oligoceno superior da Carolina do Sul.


Colónia de Albatrozes-de-laysan, por Lionel Walter Rothschild.
Similar a esta forma seriam os Plotornis, antes considerados como petréis mas que hoje são aceites como pertencendo à família dos albatrozes, do Mioceno médio francês - época em que a separação dos quatro géneros actuais já estaria em decurso, como é evidenciado pelos fósseis de Phoebastria californica e Diomedea milleri, ambos do Mioceno médio de Sharktooth Hill, na Califórnia. Isto demonstra que a separação dos grandes albatrozes dos albatrozes do Pacífico Norte terá ocorrido há 15 milhões de anos atrás. Fósseis semelhantes, encontrados no hemisfério sul levam a datar a separação entre o género Thalassarche e os piaus há 10 milhões de anos atrás.[2]

O registo fóssil de albatrozes no hemisfério norte é mais completo que no hemisfério sul, sendo muitas das formas fósseis originárias do Atlântico norte, onde estas aves não existem actualmente. Vestígios de uma colónia de albatrozes-de-cauda-curta foram descobertos numa ilha das Bermudas,.[10] A maioria dos fósseis de albatroz do Atlântico Norte teriam, de facto, pertencido ao género Phoebastria (ou albatrozes do Pacífico Norte). Um deles, Phoebastria anglica, foi encontrado em depósitos na Carolina do Norte e na Inglaterra. [carece de fontes]

Morfologia e voo

Ao contrário da maioria dos Procellariiformes, os albatrozes, como este albatroz-patinegro, conseguem deslocar-se com facilidade no solo.
Os albatrozes constituem um grupo de aves de grande a muito grande porte, sendo os maiores dos Procellariiformes. O bico é grande, forte e aguçado nas extremidades, com a mandíbula superior a terminar num grande gancho, de forma a facilitar a captura de presas de corpo liso e rápido. O bico é composto de várias placas córneas (ranfotecas) distintas e, lateralmente, apresenta duas narinas tubulosas na forma de dois tubos que acompanham as faces laterais do bico, por onde fazem excreção de sal (e que davam o antigo nome da ordem: Tubinares). As narinas tubulosas de todos os albatrozes dispõem-se ao longo dos dois lados do bico, ao contrário dos outros Procellariiformes, em que os tubos apenas se dispõem no topo do bico. Estes tubos permitem, ainda, que os albatrozes tenham um sentido do olfacto especialmente desenvolvido, o que é raro entre as aves. Como os outros Procellariiformes, usam esta sua capacidade olfactiva enquanto procuram alimento.[11] As patas não têm dedo oposto na parte posterior e os três dedos anteriores estão totalmente unidos por uma membrana interdigital, que lhes permite nadar, bem como pousar e decolar, deslizando sobre a água. As patas são particularmente fortes, tendo em conta que entre os Procellariiformes, apenas eles e os petréis-gigantes conseguem andar com eficiência em terra.[12]

A plumagem adulta da maior parte dos albatrozes é, geralmente, caracterizada pela parte superior das asas, que se apresenta escura, enquanto a parte inferior é branca. Esta característica apresenta-se de forma diferente consoante as espécies, desde o albatroz-real-meridional, que é quase totalmente branco excepto nas pontas e extremidade posterior das asas, em machos que já atingiram a maturidade, até ao albatroz-de-amsterdam com plumagem muito semelhante à juvenil, com uma grande predominância de castanhos, em especial numa banda acentuada em torno do peito. Muitas espécies do género Thalassarche e albatrozes do Pacífico Norte têm ainda marcas faciais, como manchas oculares, ou manchas cinzentas ou amarelas na cabeça e nuca. Três espécies de albatroz, o albatroz-patinegro e os piaus, fogem por completo aos padrões habituais, sendo quase totalmente revestidos de castanho-escuro (ou cinzento escuro em determinados locais, como no caso do piau-de-costa-clara). A plumagem pode levar vários anos até tomar a forma adulta definitiva.[2]

A envergadura de asa dos maiores albatrozes (do género Diomedea) ultrapassa a de qualquer outra ave, excedendo os 340 cm, ainda que a família inclua espécies com envergaduras bem menores. As asas são firmes e convexas, com a parte frontal espessa e aerodinâmica. Os albatrozes percorrem grandes distâncias recorrendo a duas técnicas de voo habituais em muitas aves marinhas de grandes asas: o voo dinâmico e o voo de talude. O voo dinâmico permite minimizar o esforço necessário para deslizar frente às ondas, utilizando o ímpeto vertical devido ao gradiente de vento. No voo de talude, o albatroz enfrenta o vento, ganhando altitude, podendo, em seguida, deslizar directamente para a superfície do oceano. Os alabatrozes têm uma razão de planeio elevada, de cerca 1:22 a 1:23, o que significa que a cada metro de altitude que descem, avançam 22 a 23 metros. São ajudados, no voo planado, pelo facto de apresentarem uma membrana tendinosa que mantém a asa distendida depois de estar totalmente aberta, sem que seja necessário fazer qualquer esforço muscular adicional. Esta adaptação morfológica é partilhada com os petréis-gigantes.[13]


A decolagem é uma das poucas fases em que os albatrozes necessitam de bater as asas para voar, sendo igualmente a fase mais exigente em termos energéticos de qualquer excursão efectuada por estas aves.
Os albatrozes combinam estas técnicas de voo planado com o uso de sistemas inatos de predição do estado do tempo. Os albatrozes do hemisfério sul que voam para norte a partir das suas colónias seguem uma rota no sentido dos ponteiros do relógio, enquanto que aqueles que voam para sul seguem o sentido contrário.[12] São aves tão bem adaptadas ao seu estilo de vida que apresentam níveis de frequência cardíaca em voo aproximados aos registados durante os períodos de repouso. Esta eficiência funcional é tal que não são as grandes distâncias percorridas numa excursão em busca de comida que implicam maior gasto energético mas, tão somente, os momentos de decolagem, aterragem e de captura do alimento - fases essas que exigem um maior esforço muscular por parte da ave.[14] Estas eficientes e longas viagens de longa distância justificam que se considere o albatroz como um bem adaptado caçador-recolector de longas distâncias, tendo em conta que o seu alimento se encontra esparsamente distribuído no oceano. A sua adaptação ao voo planado torna-os, contudo, dependentes da existência de vento e de ondas. A maioria das espécies não tem condições morfofisiológicas (isto é, de forma e funcionamento) que lhes permitam manter um voo activo auto-sustentado. Em situação de calmaria, os albatrozes são obrigados a permanecer em repouso na superfície da água até que se levantem novas ondas. Dormem apenas quando repousam sobre a água, e não enquanto voam, como alguns autores chegaram a sugerir. Os albatrozes do Pacífico Norte podem usar um estilo de voo em que alternam momentos em que batem as asas energicamente (e ganham altitude) com momentos de planeio.[15] Quando decolam, os albatrozes necessitam de efectuar uma corrida de modo a permitir a passagem suficiente de ar sob as asas para que se crie a sustentação aerodinâmica necessária para levantar voo.[16]

Embora alguns estudos apontem para a possibilidade dos albatrozes dormirem durante o voo ,[17] tal facto ainda não foi demonstrado na natureza.[18][19]

Distribuição geográfica
A maior parte dos albatrozes distribuem-se no hemisfério sul, desde a Antártida até à Austrália, África do Sul e América do Sul. As excepções incluem as quatro espécies do Pacífico Norte, sendo três exclusivamente desta região, do Hawaii ao Japão, Califórnia e Alasca; e uma, o albatroz-das-galápagos, que procria nas Ilhas Galápagos, mas que se alimenta nas costas sul americanas. A dependência em relação ao vento, necessário ao voo, justifica a confinação a latitudes elevadas, já que estas aves não têm capacidade para efectuar voo auto-sustentado, de modo a conseguir cruzar com alguma facilidade a zona de convergência intertropical. A única excepção, o albatroz-das-galápagos, é capaz de viver em águas equatoriais em volta das Ilhas Galápagos devido às águas frias da Corrente de Humboldt e ventos daí resultantes.[2]


Os albatrozes distribuem-se por grandes áreas oceânicas e efectuam regularmente viagens circumpolares.
Não se sabe ao certo porque é que os albatrozes se extinguiram no Atlântico Norte, ainda que uma subida do nível médio das águas do mar devido a um período de aquecimento interglacial tenha podido levar à submersão de uma colónia de albatrozes-de-cauda-curta escavada nas Bermudas.[10] Algumas espécies meridionais aparecem, contudo, ocasionalmente no Atlântico Norte, permanecendo aí em situação de "exílio" durante décadas. Destes espécimes exilados, há registo de um albatroz-de-sobrancelha que persistiu em voltar a uma colónia de gansos-patolas na Escócia numa tentativa vã de procriar.[20]

O uso de rastreio por satélite tem permitido aos cientistas uma recolha significativa de dados sobre as viagens em busca de alimento efectuada pelos albatrozes pelo oceano. Não procedem a qualquer migração anual, mas dispersam-se depois da época de reprodução, no caso das espécies meridionais, realizando frequentes viagens circumpolares.[21] Há ainda indícios de que as áreas de distribuição de diferentes espécies são distintas. A comparação dos nichos ecológicos de duas espécies que se reproduzem na Ilha de Campbell: o albatroz-de-campbell e o albatroz-de-cabeça-cinza, demonstra que o primeiro alimenta-se principalmente na Plataforma de Campbell enquanto que o segundo procura águas com características marcadamente oceânicas e pelágicas. O albatroz-gigante reage, também, de forma acentuada à batimetria, alimentando-se apenas em águas com uma profundidade superior a 1000 m - os dados obtidos por satélite configuram uma área com contornos de tal modo definidos que um cientista chegou a dizer que "quase parece que as aves vêem e obedecem a um sinal de "entrada proibida" nos locais onde a água tem menos de 1000 metros de profundidade".[2] Sugere-se ainda que, até na mesma espécie, os dois sexos podem ter áreas de distribuição distintas. Um estudo realizado sobre albatrozes-de-tristão que procriam na Ilha Gough demonstrou que os machos viajam para oeste enquanto que as fêmeas tomam o sentido contrário.[2]

Alimentação
A dieta dos albatrozes é dominada pelos cefalópodes, peixe e crustáceos, ainda que procedam à captura de cadáveres - incluindo restos de comida lançados de navios, que seguem por muito tempo - e à recolha de zooplâncton.[12] Note-se que para um grande número de espécies só se conhece a dieta seguida durante o período de procriação, altura em que os albatrozes voltam regularmente a terra, tornando o seu estudo possível. A importância de cada um dos tipos de alimento referidos varia muito de espécie para espécie, e mesmo de população para população. Enquanto que alguns baseiam a sua alimentação em lulas, outros preferem krill ou peixe. Das duas espécies de albatroz encontradas no Hawaii, uma, o albatroz-patinegro, prefere peixe, enquanto que o albatroz-de-laysan captura essencialmente lulas.[12]


Os piaus-de-costa-clara conseguem mergulhar regularmente até 12 metros de profundidade, de modo a capturar o seu alimento.
O uso de aparelhos que procedem ao registo da ingestão de água pelos albatrozes ao longo do tempo enquanto permanecem no oceano (o que permite fazer inferências quanto aos seus hábitos alimentares) sugere que os albatrozes se alimentam preferencialmente durante o dia. A análise de bicos de lula regurgitados por albatrozes mostrou que muitas das lulas comidas eram demasiado grandes para se poder supor que fossem capturadas vivas,[22] além de incluirem espécies que vivem na zona mesopelágica cuja profundidade está fora do alcance dos albatrozes, sugerindo que, para algumas espécies (como o albatroz-errante), a necrofagia de lulas é parte importante da sua dieta. A origem destas lulas mortas é ainda muito debatida. Alguns autores apontam a pesca humana como sendo a principal fonte, ainda que a principal causa natural seja a morte após a desova das lulas e os vómitos de lulas por parte de baleias (cachalotes, baleias-piloto e botinhosos-do-sul). A dieta de outras espécies, como o albatroz-de-sobrancelha ou o albatroz-de-cabeça-cinza, é composta essencialmente de pequenas espécies de lulas que têm a tendência a ir ao fundo depois de mortas, pelo que se assume que a necrofagia não é predominante nestas espécies.[2]

Até há pouco tempo julgava-se que os albatrozes eram predominantemente recolectores de superfície, nadando à face das águas, apanhando as lulas e peixes trazidos à superfície por correntes, predadores ou devido à sua morte. O desenvolvimento de medidores capilares de profundidade, que registam a profundidade máxima atingida por uma ave e que são colocados junto ao corpo da mesma e recolhidos quando esta volta a terra, mostram que enquanto algumas espécies, como o albatroz-errante, não mergulham mais que a um metro de profundidade, outras espécies, como o piau-de-costa-clara, atingem profundidades médias da ordem dos 5 metros, podendo chegar aos 12,5 metros.[23] Entretanto, já houve registo de observações de albatrozes que mergulham do ar em direcção à água para capturar presas.[24]

É interessante verificar que os albatrozes apresentam sintomas de enjoo, vomitando, quando estão a bordo de navios.[25]

Reprodução

Phoebastria irrorata em parada nupcial.
Os albatrozes são aves marítimas coloniais, que nidificam geralmente em ilhas isoladas. Em territórios de carácter mais continental, encontram-se em promontórios com boa acessibilidade para o mar em praticamente todas as direcções, como na Península de Otago em Dunedin, na Nova Zelândia. As colónias variam desde agregados muito densos, típicas dos albatrozes do género Thalassarche, como nas colónias de albatrozes-de-sobrancelha (nas Malvinas têm uma densidade média de 70 ninhos por 100 m²), até grupos menores e com ninhos individuais mais espaçados, típicos dos piaus e dos grandes albatrozes. Todas as colónias de albatrozes situam-se em ilhas que, em termos históricos, se apresentavam livres de mamíferos. Os albatrozes são muito filopátricos, o que significa que geralmente voltam para a sua colónia natal para procriar. Esta tendência é tão forte que um estudo sobre albatrozes-de-laysan demonstrou que a distância média entre o local de eclosão do ovo e o local onde a ave estabelece o seu próprio território é de 22 metros.[26]

Como muitas outras aves marinhas, apresenta uma estratégia demográfica de tipo selecção "K", isto é, baixa natalidade, compensada por uma longevidade relativamente grande: atrasam a altura de procriar para mais tarde, investindo maiores esforços no acompanhamento dos mais jovens. Os albatrozes têm um período de vida relativamente prolongado. A maior parte das espécies vive mais de 50 anos. O espécime com maior longevidade registada foi um albatroz-real-setentrional anilhado em adulto e que sobreviveu por mais 51 anos, o que permite estimar que tenha vivido cerca de 61 anos.[27] Dado que a maior parte de projectos científicos de anilhagem de albatrozes é mais recente que neste caso, é provável que se venha a descobrir que outras espécies têm uma maior longevidade. [carece de fontes]


Apontar para o céu é um dos gestos estereotipados das danças típicas da parada nupcial dos albatrozes-de-laysan.
Os albatrozes atingem a maturidade sexual tardiamente, com cerca de cinco anos de idade, mas mesmo depois de atingirem a maturidade, não acasalam por mais alguns anos (mais de 10, em algumas espécies). Os albatrozes jovens, ainda não preparados para acasalar, retornam por vários anos às colónias apenas para praticar os elaborados rituais de acasalamento e as danças pelas quais esta família de aves é famosa.[28] As aves que voltam pela primeira vez à colónia já apresentam os comportamentos estereotipados que compõem a sua linguagem, mas são ainda incapazes de interpretar esses mesmos comportamentos quando exibidos por outros, nem responder de forma apropriada.[12] Depois de um período de aprendizagem por tentativa e erro, as jovens aves começam a entender a sintaxe própria destes comportamentos e aperfeiçoam as dança. Esta linguagem será dominada mais rapidamente se estiverem em contacto com as aves mais velhas. [carece de fontes]

O repertório destes comportamentos envolve actuações sincronizadas de acções diversas, como gestos de higiene pessoal (catar-se), apontar para determinadas direcções, chamamentos, fazer sons batendo com os bicos, fixar o olhar em determinadas poses e combinações mais ou menos complexas destes comportamentos, como o "chamamento para o céu" (sky-call).[29] Quando um albatroz volta à colónia, dança com vários parceiros, mas, após anos sucessivos, o número de aves com que interage vai decaindo, até que é escolhido apenas um parceiro, formando-se um par monogâmico que se manterá para o resto da vida. Continuam, contudo, a aperfeiçoar a sua linguagem individual, que poderá, eventualmente, tornar-se única para esse par, ainda que parte das danças não voltem a ser, depois, usadas. [carece de fontes]

Crê-se que os albatrozes efectuam estes cuidadosos e elaborados rituais para assegurar que a escolha feita é a mais correcta e para permitir um melhor reconhecimento do seu parceiro, já que a postura do ovo e o acompanhamento da cria é um investimento importante. Mesmo espécies que conseguem completar um ciclo reprodutivo em menos de um ano raramente efectuam posturas em anos consecutivos.[2] Os grandes albatrozes levam mais de um ano a cuidar da cria desde a postura até que esta aprende a voar. Os albatrozes põem um único ovo durante a estação reprodutiva. Se o ovo for capturado por predadores ou partido acidentalmente, não haverá qualquer tentativa adicional de acasalamento nesse ano. A ocorrência de "divórcios" entre pares de albatrozes é algo de muito raro e, quando acontece, é apenas depois de vários anos de acasalamento falhado.[2]


Uma cria de albatroz no Papahānaumokuākea Marine National Monument, a maior área marinha protegida do mundo.
Todos os albatrozes meridionais fazem grandes ninhos para os seus ovos, enquanto que as três espécies do Pacífico Norte os fazem de forma mais rudimentar. O albatroz-das-galápagos, por seu lado, não faz qualquer ninho, chegando mesmo a deslocar o ovo pelo seu território por distâncias que chegam a atingir os 50 metros, provocando, por vezes, danos irreparáveis neste.[30] Em todas as espécies de albatroz, cabe aos dois progenitores a incubação do ovo em turnos que podem variar desde um dia a três semanas. A incubação dura entre 70 a 80 dias (maior para os grandes albatrozes), o que representa o maior período de incubação de qualquer ave. É um processo que pode ser particularmente exigente em termos de gastos energéticos, podendo os adultos perder cerca de 83 gramas de massa corporal por dia.[31]

Depois da eclosão, a cria é protegida pelos progenitores por três semanas até ter porte suficiente para se defender e para executar termorregulação. Durante este período, os progenitores alimentam a cria com pequenas refeições providenciadas quando rendem os turnos. A cria é alimentada em intervalos regulares pelos dois progenitores que adoptam padrões alternados de viagens curtas e longas, providenciando refeições que representam cerca de 12% do seu peso corporal (cerca de 600 g).


Os albatrozes criam os filhotes até que estes tenham porte suficiente para se defenderem e termorregularem a si mesmos (aqui, um albatroz-de-amsterdão com uma cria).
As refeições são compostas tanto por lulas, peixe e krill como por óleo estomacal, particularmente rico em energia química e cujo transporte é mais fácil que o de presas não digeridas.[32] Este óleo é produzido pelos Procellariformes num órgão estomacal conhecido como proventrículo a partir do alimento digerido, dando a estas aves um cheiro característico a mofo.[33]

As crias de albatroz levam muito tempo até aprenderem a voar. No caso dos grandes albatrozes, o processo pode levar até 280 dias. Mesmo no caso de albatrozes de menor porte, poderá demorar 140 a 170 dias.[34] Tal como no caso de muitas aves marinhas, as crias de albatroz têm de suplantar o próprio peso dos progenitores, de modo a utilizarem estas reservas suplementares para criarem condições corporais (como o crescimento de uma plumagem de voo adequada), pelo que começam a voar sensivelmente com o mesmo peso dos progenitores. Depois de aprenderem a voar, por si mesmos, deixam os progenitores por iniciativa própria. Estes, ainda assim, voltam ao local de nidificação demorando a aperceber-se que a cria já os abandonou. Estudos sobre a dispersão de aves jovens pelo oceano sugerem que exista um comportamento migratório inato, como uma rota de navegação codificada geneticamente, que as ajuda a orientarem-se no mar.[35]

Os albatrozes e o ser humano
Etimologia
O nome albatroz deriva do árabe al-câdous ou al-ġaţţās (um pelicano; que significa, literalmente, "o mergulhador"), que foi adoptado para o inglês pelo termo português alcatraz (ou "ganso-patola") - o mesmo que deu origem à famosa prisão da Ilha de Alcatraz. O Dicionário de Oxford comenta que a palavra alcatraz foi originalmente aplicado às fragatas; a modificação para albatroz foi provavelmente influenciada pelo termo latino albus, que significa "branco", em contraste com as fragatas que são negras.[12] A palavra portuguesa albatroz é de origem inglesa. [carece de fontes]

Estas aves foram ainda conhecidas pelo termo em inglês Goonie birds ou Gooney birds, especialmente para se referir aos albatrozes do Pacífico Norte. No hemisfério sul, o nome mollymawk é ainda muito utilizado em algumas áreas geográficas, sendo uma corruptela de malle-mugge, um nome neerlandês para o fulmar-glacial. O nome da família, Diomedea, dado por Lineu faz referência à mítica metamorfose dos companheiros do guerreiro grego Diomedes em aves.[36]

Albatrozes na cultura

Gravura de Gustave Doré para a Balada do Velho Marinheiro de Coleridge.
Em "O Dicionário Khazar", Milorad Pávitch diz que "só os albatrozes se exprimem, em toda parte, com a mesma linguagem",[37] o que caracteriza bem o seu estatuto de "mais lendária das aves".[34] Um albatroz é o motivo principal da Balada do Velho Marinheiro de Samuel Taylor Coleridge, onde um albatroz é feito cativo. É também a metáfora do poeta maldito num poema de Charles Baudelaire. Foi no poema de Coleridge que o uso do albatroz como metáfora teve a sua origem: diz-se, em língua inglesa, que alguém com um fardo que se apresenta como um obstáculo para a consecução dos seus objectivos tem "um albatroz em torno do pescoço" (an albatross around their neck), que não é mais que o castigo infligido, no poema, ao marinheiro que matou o albatroz. Um cartoon no "The Economist", por Kevin Kallaugher apresentava, por exemplo, Tony Blair disfarçado de pomba da paz, fazendo referência às suas diligências para a paz no Médio Oriente, mas com um albatroz (a Guerra no Iraque) acorrentado ao pescoço[38] Devido ao poema de Coleridge tornou-se vulgar pensar que os marinheiros consideravam de mau augúrio maltratar ou matar albatrozes, o que pouco correspondia à verdade, já que os matavam frequentemente por diversão ou ódio,[20] ainda que permanecesse a superstição de que eram a encarnação de marinheiros mortos naufragados. [carece de fontes]


Albatroz - Impressão em "woodcut" - Jornal "O Panorama" edição de 1837 (Da colecção privada de Dr. Nuno Carvalho de Sousa - Lisboa)

Mais recentemente, tornaram-se parte da cultura popular, como no sketch dos Monty Python, em que John Cleese tenta vender albatrozes como se fossem gelados. No filme Serenity, a personagem River Tam é referida como sendo um albatroz (fardo). Uma famosa canção de baleeiros, registada no livro de Gale Huntington, Songs the Whalemen Sang intitula-se "The Wings of a Goney" ("as asas de um albatroz"). Em The Voyage of the Dawn Treader, o terceiro volume de "As Crónicas de Nárnia" de C.S. Lewis, é enviado um albatroz para Aslan para guiar um navio para local seguro. [carece de fontes]

Os observadores de aves apreciam particularmente os albatrozes, sendo as suas colónias marinhas cada vez mais procuradas pelos ecoturistas. São feitas viagens regulares para observação de aves marinhas pelágicas em cidades costeiras como em Monterey, Kaikoura, Wollongong e Sydney. Os albatrozes são facilmente atraídos para os barcos através do despejo de óleo de peixe no mar. As visitas às colónias podem igualmente ser muito populares: a colónia de albatrozes-reais-setentrionais de Taiaroa Head, na Nova Zelândia, atrai cerca de 40 mil visitantes por ano.[2] Outras colónias, mais isoladas, são atracções regulares em cruzeiros às ilhas sub-antárcticas. [carece de fontes]

Perigos ambientais e conservação
Apesar do seu estatuto lendário, os albatrozes têm sido particularmente dizimados directa ou indirectamente pelo ser humano. Os primeiros encontros de albatrozes e Indígenas Polinésios e Aleútes resultou na sua caça e, por vezes, na sua total extirpação de algumas ilhas, como na Ilha de Páscoa. Quando se ocorreu a Era das Grandes Navegações, começaram também a caçar albatrozes, "pescando-os" a partir dos barcos para serem comidos ou, simplesmente, disparavam contra eles por diversão.[39] Este género de desporto tornou-se particularmente popular aquando da colonização da Austrália e só começou a decair quando os navios se tornaram demasiado rápidos para permitir qualquer tipo de pesca ou caça e vários regulamentos de segurança começaram a proibir a descarga de armas. No século XIX, as colónias de albatrozes, e particularmente as do Pacífico Norte, começaram a ser pilhadas pelo comércio de penas de albatroz, levando praticamente à extinção do albatroz-de-cauda-curta. De facto, a pele e as penas de albatroz podem ser utilizadas para a produção de mantas e outros artefactos conhecidos como manufacturas de "carneiro-de-cabo".[25]


Albatroz-de-sobrancelha apanhado por um anzol de um navio espinheleiro.
Das 21 espécies de albatroz reconhecidas pela IUCN na sua Lista Vermelha, 19 estão ameaçadas (estado vulnerável (VU), em perigo (EN) ou em situação crítica (CR)), e as outras duas quase ameaçadas (NT).[40] Duas das espécies (reconhecidas pela IUCN) estão em estado crítico: o albatroz-de-amsterdam e o albatroz-de-chatham. Uma das principais ameaças é a pesca com palangre,[41] já que os albatrozes e outras aves marinhas atraídos pela fonte de alimento que é o isco são facilmente presas aos anzóis do palangre, sendo arrastadas até se afogarem. Estima-se que cerca de cem mil albatrozes sejam mortos por ano desta maneira. A pesca pirata, não regulada, torna o problema ainda mais preocupante.[2][42]

Outra ameaça para os albatrozes são as espécies introduzidas nas suas colónias, como ratos e gatos assilvestrados, que atacam ovos, crias e os próprios adultos. Os albatrozes acasalam em ilhas onde não existiam mamíferos terrestres, pelo que, ao longo da sua evolução, não desenvolveram qualquer tipo de defesa contra estes. Mesmo espécies de pequeno porte, como os ratos, podem provocar, assim, grandes danos. Na Ilha Gough, as crias de albatroz-de-tristão são atacadas e comidas vivas por ratos domésticos que são muito mais pequenos que elas.[43] As espécies introduzidas podem ainda ter efeitos indirectos: o gado, por exemplo, tem destruído a cobertura vegetal da Ilha de Amsterdam ameaçando o habitat dos albatrozes aí residentes; noutras ilhas, pelo contrário, plantas invasoras têm também contribuído para reduzir o potencial de nidificação nos habitats.[2]


Os restos de uma cria de albatroz-de-laysan apresentam artefactos de plástico ingeridos antes de esta morrer, como uma rolha de garrafa e um isqueiro.
A ingestão de despojos marítimos de plástico é outro problema partilhado por várias aves marinhas. A quantidade de plástico nos oceanos tem aumentado de forma dramática desde o primeiro registo na década de 1960, proveniente tanto de lixo lançado pelos navios como de origem continental. O plástico não é digerível, ocupa espaço no estômago (moela) que deveria ser utilizado para o alimento, além de causar uma obstrução do tubo digestivo que pode levar à morte da ave por inanição. Estudos em albatrozes do Pacífico Norte demonstram que a ingestão de plástico resulta no declínio do peso e condições corporais.[44] Estes resíduos de plástico são por vezes regurgitados e dados como alimento às crias. Um estudo em crias de albatrozes-de-laysan no Atol de Midway demonstrou que é mais frequente encontrar grandes quantidades de plástico ingerido em aves que morrem naturalmente que nas crias, saudáveis, que morrem por acidente.[45] Ainda que não seja a causa directa da morte, o plástico provoca stress psicológico e faz com que a cria se sinta satisfeita quando os progenitores a alimentam, o que reduz a quantidade de alimento posto em reserva, diminuindo as hipóteses de sobrevivência.[46]


Recolha de ovos de albatrozes-de-laysan. Fotografia de Lionel Walter Rothschild.
Cientistas, organizações ambientalistas (como a BirdLife International e seus associados, que dinamizaram a Campanha "Salvem o Albatroz") trabalham actualmente com governos e pescadores para encontrar soluções para os problemas que estas aves enfrentam. Lançar o palangre à noite; tingir o isco de azul e colocá-lo nos anzóis debaixo de água; aumentar o peso das linhas e usar dispositivos que espantem as aves são técnicas que podem reduzir consideravelmente o número de capturas acessórias.[47] Por exemplo, num estudo onde colaboraram cientistas e pescadores da Nova Zelândia, testou-se com sucesso a eficácia de um dispositivo que coloca o palangre abaixo do nível máximo de mergulho de algumas espécies em situação vulnerável.[48] Crê-se que o uso de algumas destas técnicas na pesca de merluza-negra nas Malvinas terá reduzido o número de albatrozes-de-sobrancelha apanhados pela frota pesqueira nos últimos dez anos.[49]

Outro passo importante tendo em vista a protecção dos albatrozes e outras aves marinhas foi dado com o Acordo sobre a Conservação dos Albatrozes e Petréis (Agreement on the Conservation of Albatrosses and Petrels) de 2001 que passou a vigorar em 2004 e que foi ratificado por oito países: Austrália, Equador, Nova Zelândia, Espanha, África do Sul, França, Peru e Reino Unido. O tratado dispõe que estes países efectuem acções específicas para reduzir a captura acessória e a poluição, bem como a remoção de espécies introduzidas nas ilhas onde as aves nidificam. O tratado foi também assinado, mas não ratificado pelo Brasil, Argentina e Chile.[50]